apiVersion: v1
kind: Secret
metadata:
  name: {{ include "libra.fullname" . }}-jupyter-token
  labels:
    {{- include "libra.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.jupyterToken | quote }}
