{{- if .Values.imageCredentials.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "libra.fullname" . }}-registrykey'
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
