name: ARC scaling test

on:
  workflow_dispatch:

jobs:
  scale-test:
    name: Fake build job
    runs-on: 
      group: aws-arc
      labels: aws-arc-runner-lapis-dev

    container:
      image: almalinux:latest

    strategy:
      fail-fast: false
      matrix:
        job-id: [1, 2, 3, 4, 5, 6]

    steps:
      - name: Report node properties
        run: |
          echo "host info:"
          dnf install -y procps-ng
          cat /etc/redhat-release
          uname -a
          nproc
          free -h

      - name: Perform dummy work
        run: |
          for i in $(seq 1 $(nproc)); do
            while true; do :; done &
          done

          sleep 120
          
          kill $(jobs -p) || true
